import typescript from "./typescript";
import template from "./template";

export default {
  typescript: {
    extends: [
      "plugin:@typescript-eslint/recommended",
      "plugin:@typescript-eslint/recommended-requiring-type-checking",
      "plugin:@typescript-eslint/strict",
      "plugin:@angular-eslint/recommended",
      "plugin:@angular-eslint/template/process-inline-templates",
    ],
    rules: {
      "@angular-eslint/component-class-suffix": [
        "error",
        { suffixes: ["Component", "Modal", "Page"] },
      ],
      "@angular-eslint/component-max-inline-declarations": "error",
      "@angular-eslint/component-selector": [
        "error",
        { type: "element", style: "kebab-case" },
      ],
      "@angular-eslint/consistent-component-styles": "error",
      "@angular-eslint/contextual-decorator": "error",
      "@angular-eslint/contextual-lifecycle": "error",
      "@angular-eslint/directive-class-suffix": "error",
      "@angular-eslint/directive-selector": [
        "error",
        { type: "attribute", style: "camelCase" },
      ],
      "@angular-eslint/no-async-lifecycle-method": "error",
      "@angular-eslint/no-attribute-decorator": "error",
      "@angular-eslint/no-conflicting-lifecycle": "error",
      "@angular-eslint/no-empty-lifecycle-method": "error",
      "@angular-eslint/no-forward-ref": "error",
      "@angular-eslint/no-input-prefix": ["error", { prefixes: ["on"] }],
      "@angular-eslint/no-input-rename": "error",
      "@angular-eslint/no-inputs-metadata-property": "error",
      "@angular-eslint/no-lifecycle-call": "error",
      "@angular-eslint/no-output-native": "error",
      "@angular-eslint/no-output-on-prefix": "error",
      "@angular-eslint/no-output-rename": "error",
      "@angular-eslint/no-outputs-metadata-property": "error",
      "@angular-eslint/no-pipe-impure": "error",
      "@angular-eslint/no-queries-metadata-property": "error",
      "@angular-eslint/prefer-output-readonly": "error",
      "@angular-eslint/prefer-standalone": "error",
      "@angular-eslint/relative-url-prefix": "error",
      "@angular-eslint/sort-lifecycle-methods": "error",
      "@angular-eslint/sort-ngmodule-metadata-arrays": "error",
      "@angular-eslint/use-component-view-encapsulation": "error",
      "@angular-eslint/use-injectable-provided-in": "error",
      "@angular-eslint/use-lifecycle-interface": "error",
      "@angular-eslint/use-pipe-transform-interface": "error",
      "@typescript-eslint/return-await": "error",
      "@typescript-eslint/lines-between-class-members": [
        "error",
        "always",
        { exceptAfterSingleLine: true },
      ],
      "@typescript-eslint/member-ordering": "error",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-extraneous-class": [
        "error",
        { allowEmpty: true, allowStaticOnly: true },
      ],
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: false },
      ],
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/prefer-destructuring": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/sort-type-constituents": "error",
      "@typescript-eslint/unbound-method": ["error", { ignoreStatic: true }],
    },
  },
  template: {
    extends: ["plugin:@angular-eslint/template/recommended"],
    rules: {
      "@angular-eslint/template/attributes-order": [
        "error",
        { alphabetical: true },
      ],
      "@angular-eslint/template/banana-in-box": "error",
      "@angular-eslint/template/conditional-complexity": "error",
      "@angular-eslint/template/cyclomatic-complexity": [
        "error",
        { maxComplexity: 10 },
      ],
      "@angular-eslint/template/elements-content": "error",
      "@angular-eslint/template/eqeqeq": "error",
      "@angular-eslint/template/label-has-associated-control": "error",
      "@angular-eslint/template/mouse-events-have-key-events": "error",
      "@angular-eslint/template/no-any": "error",
      "@angular-eslint/template/no-autofocus": "error",
      "@angular-eslint/template/no-call-expression": "error",
      "@angular-eslint/template/no-distracting-elements": "error",
      "@angular-eslint/template/no-duplicate-attributes": "error",
      "@angular-eslint/template/no-interpolation-in-attributes": "error",
      "@angular-eslint/template/no-negated-async": "error",
      "@angular-eslint/template/no-positive-tabindex": "error",
      "@angular-eslint/template/prefer-self-closing-tags": "error",
      "@angular-eslint/template/role-has-required-aria": "error",
      "@angular-eslint/template/table-scope": "error",
      "@angular-eslint/template/use-track-by-function": [
        "error",
        { alias: ["ngForTrackByIndex", "ngForTrackByProperty"] },
      ],
      "@angular-eslint/template/valid-aria": "error",
    },
  },
};
