import stylistic from '@stylistic/eslint-plugin';
import type { Linter } from 'eslint';
import { isEmpty } from 'lodash-es';

export const getStylisticConfigs = (
  sources?: string[],
  isTests?: boolean,
): Linter.Config[] => {
  const errorWhenNotTests = !isTests ? 'error' : 'off';

  return isEmpty(sources)
    ? []
    : [
        {
          ...stylistic.configs['all'],
          files: sources,
          rules: {
            ...stylistic.configs['all'].rules,
            '@stylistic/array-bracket-newline': 'off',
            '@stylistic/array-bracket-spacing': errorWhenNotTests,
            '@stylistic/array-element-newline': 'off',
            '@stylistic/arrow-parens': 'error',
            '@stylistic/arrow-spacing': 'off',
            '@stylistic/block-spacing': 'off',
            '@stylistic/brace-style': 'error',
            '@stylistic/comma-dangle': 'off',
            '@stylistic/comma-spacing': 'error',
            '@stylistic/comma-style': 'off',
            '@stylistic/computed-property-spacing': ['error', 'never'],
            '@stylistic/curly-newline': ['error', 'always'],
            '@stylistic/dot-location': 'off',
            '@stylistic/eol-last': ['error', 'always'],
            '@stylistic/function-call-argument-newline': 'off',
            '@stylistic/function-call-spacing': ['error', 'never'],
            '@stylistic/function-paren-newline': 'off',
            '@stylistic/generator-star-spacing': 'off',
            '@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
            '@stylistic/indent': 'off',
            '@stylistic/indent-binary-ops': 'off',
            '@stylistic/jsx-child-element-spacing': 'off',
            '@stylistic/jsx-closing-bracket-location': 'off',
            '@stylistic/jsx-closing-tag-location': 'off',
            '@stylistic/jsx-curly-brace-presence': 'off',
            '@stylistic/jsx-curly-newline': 'off',
            '@stylistic/jsx-curly-spacing': 'off',
            '@stylistic/jsx-equals-spacing': 'off',
            '@stylistic/jsx-first-prop-new-line': 'off',
            '@stylistic/jsx-function-call-newline': 'off',
            '@stylistic/jsx-indent': 'off',
            '@stylistic/jsx-indent-props': 'off',
            '@stylistic/jsx-max-props-per-line': 'off',
            '@stylistic/jsx-newline': 'off',
            '@stylistic/jsx-one-expression-per-line': 'off',
            '@stylistic/jsx-pascal-case': 'off',
            '@stylistic/jsx-props-no-multi-spaces': 'off',
            '@stylistic/jsx-props-style': 'off',
            '@stylistic/jsx-quotes': 'off',
            '@stylistic/jsx-self-closing-comp': 'off',
            '@stylistic/jsx-sort-props': 'off',
            '@stylistic/jsx-tag-spacing': 'off',
            '@stylistic/jsx-wrap-multilines': 'off',
            '@stylistic/key-spacing': ['error', { beforeColon: false }],
            '@stylistic/keyword-spacing': ['error', { before: true }],
            '@stylistic/line-comment-position': 'off',
            '@stylistic/linebreak-style': 'off',
            '@stylistic/lines-around-comment': 'off',
            '@stylistic/lines-between-class-members': ['error', 'always'],
            '@stylistic/list-style': 'off',
            '@stylistic/max-len': 'off',
            '@stylistic/max-statements-per-line': 'off',
            '@stylistic/member-delimiter-style': 'off',
            '@stylistic/multiline-comment-style': 'off',
            '@stylistic/multiline-ternary': 'off',
            '@stylistic/new-parens': 'off',
            '@stylistic/newline-per-chained-call': 'off',
            '@stylistic/no-confusing-arrow': 'error',
            '@stylistic/no-extra-parens': 'off',
            '@stylistic/no-extra-semi': 'error',
            '@stylistic/no-floating-decimal': 'error',
            '@stylistic/no-mixed-operators': 'off',
            '@stylistic/no-mixed-spaces-and-tabs': 'error',
            '@stylistic/no-multi-spaces': 'error',
            '@stylistic/no-multiple-empty-lines': 'off',
            '@stylistic/no-tabs': 'off',
            '@stylistic/no-trailing-spaces': 'error',
            '@stylistic/no-whitespace-before-property': 'off',
            '@stylistic/nonblock-statement-body-position': 'off',
            '@stylistic/object-curly-newline': 'off',
            '@stylistic/object-curly-spacing': 'off',
            '@stylistic/object-property-newline': 'off',
            '@stylistic/one-var-declaration-per-line': 'off',
            '@stylistic/operator-linebreak': 'off',
            '@stylistic/padded-blocks': 'off',
            '@stylistic/padding-line-between-statements': 'off',
            '@stylistic/quote-props': 'off',
            '@stylistic/quotes': 'off',
            '@stylistic/rest-spread-spacing': ['error', 'never'],
            '@stylistic/semi': 'off',
            '@stylistic/semi-spacing': 'off',
            '@stylistic/semi-style': 'off',
            '@stylistic/space-before-blocks': 'error',
            '@stylistic/space-before-function-paren': 'off',
            '@stylistic/space-in-parens': 'off',
            '@stylistic/space-infix-ops': 'off',
            '@stylistic/space-unary-ops': 'off',
            '@stylistic/spaced-comment': 'off',
            '@stylistic/switch-colon-spacing': 'off',
            '@stylistic/template-curly-spacing': 'error',
            '@stylistic/template-tag-spacing': 'off',
            '@stylistic/type-annotation-spacing': 'error',
            '@stylistic/type-generic-spacing': 'off',
            '@stylistic/type-named-tuple-spacing': 'off',
            '@stylistic/wrap-iife': 'off',
            '@stylistic/wrap-regex': 'off',
            '@stylistic/yield-star-spacing': 'off',
          },
        },
      ];
};
